name: "same workflow"
on:
    push: 
        branches: 
            main
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: copy code using actions
              uses: actions/checkout@v5
            - name: setup jdk
              uses:  actions/setup-java@v5
              with:
                distribution: 'temurin'
                java-version: '21'
                cache: maven
            - name: setup jre
              run: mvn package
            - name: run tests
              uses: testspace-com/setup-testspace@v1
            - name: package application for testers
              uses: actions/upload-artifact@v4
              
              

            