name: java workflow
on:
    push: 
        branches: 
            main
    workflow_dispatch:
jobs:
    job:
        runs-on: ubuntu-22.04
        steps:
            - name: david
              env:
                  java: 17
              uses: actions/checkout@v5
            - run: mvn package