name: java workflow
on:
    push: 
        branches: 
            main
    workflow_dispatch:
jobs:
    job:
        runs-on: ubuntu-22.04
        steps:
            - name: copy code 
              uses: actions/checkout@v5
            - name: setup java
              uses: actions/setup-java@v5
              with:
                   distribution: 'temurin' 
                   java-version: '21'
                   cache: maven 
            - run: mvn package
            - name: Publish Test Results
              uses: EnricoMi/publish-unit-test-result-action@v2
              with:
                files: |
                   **/target/surefire-reports/*.xml
            - name: upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: java-petclinic-artifact
                path: |
                    **/target/*.jar
