name: java workflow
on:
    push: 
        branches: 
            main
    workflow_dispatch:
jobs:
    job:
        runs-on: ubuntu-22.04
        steps:
            - name: david
              uses: actions/checkout@v5
            - name: java setup
              uses: actions/setup-java@v5
              with:
                distribution: 'temurin'
                java-version: '17'
                cache: java
            - run: mvn package