name: "same workflow"
on:
    push: 
        branches: 
            main
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: copy code using actions
              uses: actions/checkout@v5
            - name: setup jdk
              uses:  actions/setup-java@v5
              with:
                distribution: 'temurin'
                java-version: '21'
                cache: maven
            - name: setup jre
              run: mvn package
            - name: run tests
              uses: EnricoMi/publish-unit-test-result-action@v2
              with:
                path: target/surefire-reports/*.xml
            - name: package application for testers
              uses: actions/upload-artifact@v4
              with:
                files: |
                    path: /home/runner/work/spring1/spring1/target/spring-petclinic-3.5.0-SNAPSHOT.jar

              

            