name: java workflow
on:
    push: 
        branches: 
            main
    workflow_dispatch:
jobs:
    job:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v5
            - uses: actions/setup-java@v5
              with:
                   distribution: 'temurin' # See 'Supported distributions' for available options
                   java-version: '21'
                   cache: maven a
            - run: mvn package