name: cibuild&package
on:
    push:
        branches: 
            main
    workflow_dispatch: 
      
permissions: 
  checks: write
  contents: read
jobs:
    maven:
        runs-on: ubuntu-latest
        steps:
            - name: resuableaction
              uses: actions/checkout@v5
            - uses: actions/setup-java@v5
              with:
                  distribution: "temurin"
                  java-version: "21"
                  cache: maven
            - name: mavenbuild
              run: mvn ${{ vars.Goal }}
            - name: Publish Test Results
              uses: EnricoMi/publish-unit-test-result-action@v2
              with:
                files: |
                  **/target/surefire-reports/*.xml
            - name: upload artifacts for testers
              uses: actions/upload-artifact@v4
              with: 
                name: my-artifact
                path: '**/target/*.jar'


            
 