name: java workflow
on:
    pull_request:  
        branches: 
            main
    workflow_dispatch:
env:
    buildcommand: mvn package
jobs:
    job:
        runs-on: ubuntu-22.04
        steps:
            - name: copy code 
              uses: actions/checkout@v5
            - name: initialize codeql
              uses: github/codeql-action/init@v3
              with:
                languages: java
            - name: setup java
              uses: actions/setup-java@v5
              with:
                   distribution: 'temurin' 
                   java-version: '21'
                   cache: maven 
            - uses: jfrog/setup-jfrog-cli@v4
              with:
                version: latest
              env:
               JF_URL: ${{ vars.JF_URL }}
               JF_ACCESS_TOKEN: ${{ secrets.JFROGTOKEN }}
            - name: Check JFrog CLI
              run: |
               jf --version
               jf rt ping
            - run: ${{ env.buildcommand }}
            - name: perform quality analyses
              uses: github/codeql-action/analyze@v3
            - name: publish tests
              uses: EnricoMi/publish-unit-test-result-action@v2
              with:
                files: |
                   **/target/surefire-reports/*.xml
            - name: upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: java-petclinic-artifact
                path: |
                    **/target/*.jar
            - name: Build and deploy with Maven
              run: |
                 jf mvn-config \
                 jfrog rt mvn "clean install deploy" \
                 --server-id-resolve learning-libs-release \
                 --server-id-deploy learning-libs-snapshot \
                 --build-name my-build \
                 --build-number $GITHUB_RUN_NUMBER
                 --interactive=false
